/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto.pneu.programas;

import br.com.bandtec.projeto.pneu.clienteJira.ConexaoAPIJira;
import br.com.bandtec.projeto.pneu.modelos.ConexaoBanco;
import br.com.bandtec.projeto.pneu.modelos.Issue;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author LEONARDOOLIVEIRALEAL
 */
public class TelaConsultaLocalizacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsulta
     */
    public TelaConsultaLocalizacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlListaCadastro = new javax.swing.JList<>();
        jlTitulo = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlListaCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 173, 227)));
        jScrollPane1.setViewportView(jlListaCadastro);

        jlTitulo.setBackground(new java.awt.Color(151, 109, 208));
        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Localizações Cadastradas");

        jPanel10.setBackground(new java.awt.Color(35, 35, 35));

        jLabel9.setBackground(new java.awt.Color(151, 109, 208));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(3, 173, 227));
        jLabel9.setText("PNEU");

        btFechar.setBackground(new java.awt.Color(3, 173, 227));
        btFechar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFechar.setForeground(new java.awt.Color(255, 255, 255));
        btFechar.setText("Fechar");
        btFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFechar)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcluir.setBackground(new java.awt.Color(3, 173, 227));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        String selecionado = jlListaCadastro.getSelectedValue();
        
        String[] separar1 = selecionado.split(" - ");
        String[] separar2 = separar1[1].split(", ");
        String estado = separar1[0];
        String cidade = separar2[0];
        String bairro = separar2[1];
        String rua = separar2[2];
        Integer numero = Integer.parseInt(separar2[3]);
            
            
        Connection con = null;
        Integer senha_ok = 0;
        String senha = null;
        String senhaGerente = "Adm123";
        while (senha_ok == 0){
            JPasswordField pf = new JPasswordField();
            String msgJ = "Digite a senha de Gerente";
            Integer okCxl = JOptionPane.showConfirmDialog(null, pf, msgJ, JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (okCxl == 0) {
                try {
                    senha = new String(pf.getPassword());
                    // Tenta conexão com banco MySql
                    Class.forName(ConexaoBanco.DRIVER);
                    con = DriverManager.getConnection(ConexaoBanco.URL, ConexaoBanco.USER, ConexaoBanco.PASSWORD);
                    
                    if (senha.equals(senhaGerente)){
                        try {
                            Class.forName(ConexaoBanco.DRIVER);
                            con = DriverManager.getConnection(ConexaoBanco.URL, ConexaoBanco.USER, ConexaoBanco.PASSWORD);
                            Statement stm = con.createStatement();
                            String SQLSelectServidor = "select * from Localizacao;";
                            ResultSet rsServidor = stm.executeQuery(SQLSelectServidor);
                            while(rsServidor.next()) {
                                Statement stm1 = con.createStatement();
                                String SQLSelectComponente = "select * from Servidor;";
                                ResultSet rsComponente = stm1.executeQuery(SQLSelectComponente);
                                while(rsComponente.next()) {
                                    String query = "delete from Componente where fkServidor = ?";
                                    PreparedStatement preparedStmt = con.prepareStatement(query);
                                    preparedStmt.setString(1, rsComponente.getString("idServidor"));
                                    
                                    preparedStmt.execute();
                                }
                                
                                String query = "delete from Servidor where fkLocalizacao = ?";
                                PreparedStatement preparedStmt2 = con.prepareStatement(query);
                                preparedStmt2.setString(1, rsServidor.getString("idLocalizacao"));
                                
                                preparedStmt2.execute();
                            }
                            
                            String query = "delete from Localizacao where estado = ? and cidade = ? and bairro = ? and rua = ? and numero = ?;";
                            PreparedStatement preparedStmt3 = con.prepareStatement(query);
                            preparedStmt3.setString(1, estado);
                            preparedStmt3.setString(2, cidade);
                            preparedStmt3.setString(3, bairro);
                            preparedStmt3.setString(4, rua);
                            preparedStmt3.setInt(5, numero);
                            
                            preparedStmt3.execute();
                            
                            String SQLSelect = "select * from Localizacao;";
                            ResultSet rs = stm.executeQuery(SQLSelect);
                            DefaultListModel dlm = new DefaultListModel();
                            while(rs.next()) {
                                dlm.addElement(rs.getString("estado")+" - "+rs.getString("cidade")+", "+rs.getString("bairro")+", "+rs.getString("rua")+", "+rs.getString("numero"));
                            }
                            jlListaCadastro.setModel(dlm);
                            
                            JOptionPane.showMessageDialog(null,"A localização selecionada foi deletada","Localização deletada",JOptionPane.INFORMATION_MESSAGE);
                            
                            String msg = "A localização "+estado+" - "+cidade+", "+bairro+", "+rua+", "+numero+" foi deletada.";
                            try {
                                Issue novaIssue = new Issue();
                                novaIssue.setProjectKey("BDJ");
                                novaIssue.setSummary(msg);
                                novaIssue.setDescription("Cadastro de localização foi executado");
                                ConexaoAPIJira.criacao(novaIssue);
                                
                                Gson gson = new GsonBuilder().setPrettyPrinting().create();
                                System.out.println("Issue criada: "+gson.toJson(novaIssue));
                            } catch (IOException ex) {
                                Logger.getLogger(TelaServidor.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
                        } catch (ClassNotFoundException | SQLException ex) {
                            Logger.getLogger(TelaConsultaComponente.class.getName()).log(Level.SEVERE, null, ex);
                        }
                            senha_ok++;
                        }
                        } catch (ClassNotFoundException | SQLException ex) {
                            Logger.getLogger(TelaConsultaLocalizacao.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        senha_ok++;
                    }
                    if (senha.equals("")){
                        JOptionPane.showMessageDialog(null, "Senha não preenchida");
                    } else if (senha_ok == 0){
                        JOptionPane.showMessageDialog(null, "Senha incorreta");
                    }
        }               
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaConsultaLocalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaConsultaLocalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaConsultaLocalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaConsultaLocalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaConsultaLocalizacao().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JList<String> jlListaCadastro;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
